### ISSUE TITLE
Indicating presence of IANA registered link in API and not violating definition

### ISSUE THREAD

**Issue by fosdev** [alps-io/spec#33]
Should an ALPS document be allow to indicate say a `edit` descriptor for a `idempotent` transition in such a way that allows a client to know it is part of the profile, but not override the Atom IANA definition. Or are we limited to just saying "a client should just understand that" and not include it in a profile? Seems the latter is less than desirable.

**Comment by fosrias** [comment]
So, what I am saying here is if I want to add `edit` in my profile, so that a client or whoever knows that is one of the semantic elements, how do I ensure that it means the same thing as the IANA definition absent wording to enforce that. Seems we may have addressed this, and it may relate to https://github.com/alps-io/spec/issues/67.

Should we close this one and move the discussion to https://github.com/alps-io/spec/issues/67?

**Comment by mamund** [comment]
closed -- covered in #67
