### ISSUE TITLE
add TYPE property to EXT element

### ISSUE THREAD

**Issue by mamund** [alps-io/spec#90]
i've found a handful of times that i need to mark EXT elements with TYPE information to help reader/writer tooling.  This will be a single string property that can contain any valid string text. the meaning of that value can be documented when documenting the EXT element itself.

```xml
<ext id="hatSize" type="enum" value="large medium small really-big" />
```

this may also help with issue #8

**Comment by filip26** [comment]
If `type` value range is not defined by the specification then it adds just a little value, because it is expected that a client/processor 'knows' but if a client knows then it can know an unspecified `type` attribute.

if the type value range is defined then I'm thinking maybe introducing other elements could be more readable.

e.g.
```xml
<enum id="hatSize" value="...."/>
```
I personally like keeping the spec simple. Let's discuss it.

**Comment by mamund** [comment]
we can discuss this in the weekly AOOH. I'm OK w/ dropping the TYPE element for EXT if it complicates things.

**Comment by mamund** [comment]
not for now.

**Comment by mamund** [comment]
closed out
